apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: busybox:stable
    command: ["/bin/sh","-c","env"] # Se muestran las variables de entorno al ejecutar el pod
    env: # Ac√° se definen las variables de entorno
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: mi-config # nombre del config
            key: special.how # nombre de la clave a introducir
  restartPolicy: Never