apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
  # Especificamos donde se montará el volumen
    volumeMounts:
    - mountPath: /redis-master
      name: config #nombre del volúmen

  volumes:
    - name: config
      configMap:
        name: example-redis-config
        items:
        - key: redis-config # nombre para el volúmen
          path: redis.conf # ubicación donde la información se presentará en el pod