apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-proyecto
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /clima
        pathType: Prefix
        backend:
          service:
            name: api-rust-service
            port:
              number: 80