apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go-deploy
  labels:
    app: api-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-go
  template:
    metadata:
      labels:
        app: api-go
    spec:
      containers:
      - name: api-go
        # Usa la URL de ngrok que se obtuvo
        image: c8507ebd5490.ngrok-free.app/api-go
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GRPC_SERVER_ADDR
          value: "grpc-server-service:50051"
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-service
  labels:
    app: api-go
spec:
  selector:
    app: api-go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080